animal:
  names:
    bearNames:
      - MICHAEL
      - STEVE
      - HENRY
    catNames:
      - VASYA
      - ALISA
      - LILU
    parrotNames:
      - KESHA
      - TOM
      - JERRY
    wolfNames:
      - WOOFY
      - BITTY
      - LEO
    allNames:
      - MICHAEL
      - STEVE
      - HENRY
      - VASYA
      - ALISA
      - LILU
      - KESHA
      - TOM
      - JERRY
      - WOOFY
      - BITTY
      - LEO

